ConfigVersion:
#If ProtectTames is true, it will protect the tamed mobs of players from being damaged by players other than the owner.
ProtectTames:
#If Allow Transfers is true, it will allow players with the appropriate permission to transfer their own tames.
AllowTransfers:
#If AllowReleases is true, it will allow players with appropriate permission to release their own animals.
AllowReleases:
#If ProtectHorses is true, players will not be able to ride another player's horse or open horse inventory.
ProtectHorses:
#Toggling any of the Breeding Options to false will make it so players cannot breed that animal. (Tamed Animals Only)
Breeding:
  Horse:
  Wolf:
  Ocelot: 